### ISSUE TITLE
播放器

### ISSUE THREAD

**Issue by Attractively** [ZhangHangTao/MusicPlayer#1]
您好，请问一下可以使用一下你的这个音乐播放器的源码吗？

**Comment by Rookie143** [comment]
可以的，开源精神



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月19日(周二) 晚上11:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)




 
您好，请问一下可以使用一下你的这个音乐播放器的源码吗？

**Comment by Attractively** [comment]
谢谢啦，但是这个文件里面是不是没有这个系统里面要用到的图片啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangHangTao/MusicPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 晚上11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)





 可以的，开源精神 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年4月19日(周二) 晚上11:33 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1) 
 
 
 
 
   
 您好，请问一下可以使用一下你的这个音乐播放器的源码吗？

**Comment by Attractively** [comment]
请问可以求一下这个系统要用到的图片吗

**Comment by Rookie143** [comment]
> 

请问你指的图片是什么，系统用的到图片都在[MusicPlayer]MusicPlayer/bin/cn/res/img/ 中(如果我项目上传完整的话)

**Comment by Attractively** [comment]
不好意思，我找到， 是我这边解析有问题，真的谢谢啦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hangtao ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)





   
请问你指的图片是什么，系统用的到图片都在[MusicPlayer]MusicPlayer/bin/cn/res/img/ 中(如果我项目上传完整的话)

**Comment by Rookie143** [comment]
okok，这个项目用IDEA导了包以后应该能轻松配置，我试过，Eclipse则比较麻烦。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangHangTao/MusicPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)





 不好意思，我找到， 是我这边解析有问题，真的谢谢啦 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "hangtao ***@***.***&amp;gt;;  
 发送时间: 2022年4月20日(星期三) 下午3:11 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1) 
 
 
 
 
 
     
 请问你指的图片是什么，系统用的到图片都在[MusicPlayer]MusicPlayer/bin/cn/res/img/ 中(如果我项目上传完整的话)

**Comment by Attractively** [comment]
恩恩额 ，是的 ，我直接用的IDEA ，就是开始的问题就是一运行那个bin目录下面的图片文件就没有了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangHangTao/MusicPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)





 okok，这个项目用IDEA导了包以后应该能轻松配置，我试过，Eclipse则比较麻烦。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ZhangHangTao/MusicPlayer"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年4月20日(星期三) 下午3:25 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1) 
 
 
 
 
 
  不好意思，我找到， 是我这边解析有问题，真的谢谢啦  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "hangtao ***@***.***&amp;amp;gt;;   
  发送时间: 2022年4月20日(星期三) 下午3:11  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)  
   
   
   
   
   
       
  请问你指的图片是什么，系统用的到图片都在[MusicPlayer]MusicPlayer/bin/cn/res/img/ 中(如果我项目上传完整的话)

**Comment by Attractively** [comment]
真的感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangHangTao/MusicPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhangHangTao/MusicPlayer] 播放器 (Issue #1)





 
Closed #1.
